### ISSUE TITLE
Go1.13 golang.org/cl/161477 will break Decompress1X runtime error handling

### ISSUE THREAD

**Issue by cybrcodr** [rasky/go-lzo#7]
Upcoming Go 1.13 change https://golang.org/cl/161477 updates the runtime error strings for index out of range errors, which breaks the assumption that Decompress1X func has on it at https://github.com/rasky/go-lzo/blob/master/decompress.go#L160.

```
$ go version
$ go version devel +431b5c69ca Tue Apr 16 21:54:01 2019 +0000 darwin/amd64
$ go test
--- FAIL: TestDecompInlen (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0

goroutine 20 [running]:
testing.tRunner.func1(0xc0000e8100)
        /Users/herbie/work/go113/go/src/testing/testing.go:830 +0x3a3
panic(0x115b440, 0xc00010a020)
        /Users/herbie/work/go113/go/src/runtime/panic.go:619 +0x1b2
github.com/rasky/go-lzo.Decompress1X.func1(0xc000106e70)
        /Users/herbie/work/google3-go/lzo/decompress.go:165 +0xfa
panic(0x115b440, 0xc00010a020)
        /Users/herbie/work/go113/go/src/runtime/panic.go:619 +0x1b2
github.com/rasky/go-lzo.(*reader).ReadU16(...)
        /Users/herbie/work/google3-go/lzo/decompress.go:94
github.com/rasky/go-lzo.Decompress1X(0x1199c40, 0xc0000c2040, 0x31, 0x0, 0xc0000d6090, 0xf, 0x10, 0x0, 0x0)
        /Users/herbie/work/google3-go/lzo/decompress.go:234 +0x944
github.com/rasky/go-lzo.TestDecompInlen(0xc0000e8100)
        /Users/herbie/work/google3-go/lzo/compress_test.go:126 +0x20c
testing.tRunner(0xc0000e8100, 0x1177800)
        /Users/herbie/work/go113/go/src/testing/testing.go:865 +0xbf
created by testing.(*T).Run
        /Users/herbie/work/go113/go/src/testing/testing.go:916 +0x350
exit status 2
FAIL    github.com/rasky/go-lzo 0.024s
```

I'll send a PR to update the check.

**Comment by tbarbugli** [comment]
we got bitten by the same problem

**Comment by tbarbugli** [comment]
here's our fork with this problem patched https://travis-ci.org/GetStream/go-lzo

**Comment by rasky** [comment]
I've merged the PR, sorry for the delay, I had missed it.
